name: Replace all variables in the docs
description: |
  Replace all variables in the docs

inputs:
  VERSION:
    description: |
      The current version
  VERSION_TYPE:
    description: |
      The type of the build.
    required: true
  VERSION_MAVEN:
    description: |
      The version of the build in maven format.
    required: true
  REPOSITORY_URL:
    description: |
      The maven repository url.
    required: true

runs:
  using: composite
  steps:
    - uses: BetonQuest/Workflows/.github/actions/replace-docs-variables@main
      with:
        VERSION: ${{ inputs.VERSION }}
    - name: Set API/Overview.md version
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sed -i "s~\${betonquest\.version}~${VERSION_MAVEN}~g" ./docs/API/Overview.md
      env:
        VERSION_MAVEN: ${{ inputs.VERSION_MAVEN }}
    - name: Set ref in download commands
      if: "inputs.VERSION_TYPE == 'release' || inputs.VERSION_TYPE == 'development'"
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        if [ $VERSION_TYPE == 'release' ]; then REFERENCE="${{ github.ref }}"; else REFERENCE="$(cd docs/_tutorials/ && git rev-parse HEAD)"; fi
        find docs/ -type f -exec sed -i "s#/bq download BetonQuest/Quest-Tutorials \${ref} QuestPackages #/bq download BetonQuest/Quest-Tutorials ${REFERENCE} QuestPackages #" {} +
      env:
        VERSION_TYPE: ${{ inputs.VERSION_TYPE }}
    - name: Set secret in downloads.js script
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sed -i "s~\${REPOSITORY_URL}~$REPOSITORY_URL~g" ./docs/_webCode/js/downloads.js
      env:
        REPOSITORY_URL: ${{ inputs.REPOSITORY_URL }}
