name: Setup Git LFS
description: |
  This action sets up Git LFS

runs:
  using: composite
  steps:
    - name: Hash LFS file list
      id: cache-hash
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        hash=$({
          git lfs ls-files --long | cut -d ' ' -f1
          git submodule foreach --quiet 'git lfs ls-files --long | cut -d " " -f1 | sed -e "s#^#${sm_path}/#"'
        } | sort | sha256sum - | cut -d' ' -f1)
        echo "hash=$hash" >> $GITHUB_OUTPUT
    - name: Cache Paths of LFS Submodules
      id: cache-paths
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        paths='.git/lfs'
        while read line; do
          paths+=$'\n'".git/modules/$line/lfs"
        done < <(git submodule foreach --quiet 'echo $name')
        printf 'paths<<EOF\n%s\nEOF\n' "$paths" >> "$GITHUB_OUTPUT"
    - name: Restore LFS cache
      uses: actions/cache@v4
      with:
        path: '${{ steps.cache-paths.outputs.paths }}'
        key: ${{ runner.os }}-lfs-${{ steps.cache-hash.outputs.hash }}-v1
    - name: Git LFS Pull
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        git lfs pull
        git submodule foreach git lfs pull
