name: Daily Dependency Check
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  artifacts:
    name: Build Artifacts
    if: "always() && github.repository == 'BetonQuest/BetonQuest'"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-maven
        with:
          JAVA_OVERRIDE_SETTINGS: 'false'
      - name: Build with Maven
        run: |
          ./mvnw -P Test-All -B package -DskipProjectSettings=true

  docs:
    name: Build Docs
    if: "always() && github.repository == 'BetonQuest/BetonQuest'"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-git-lfs
      - uses: ./.github/actions/setup-mkdocs-material
        with:
          MKDOCS_MATERIAL_INSIDERS: ${{ secrets.MKDOCS_MATERIAL_INSIDERS }}
      - name: Build with mkdocs
        run: |
          mkdocs build --strict
        env:
          MKDOCS_MATERIAL_INSIDERS_ENABLED: ${{ secrets.MKDOCS_MATERIAL_INSIDERS != '' }}
          MKDOCS_MATERIAL_INSIDERS_ENABLED_CI: ${{ secrets.MKDOCS_MATERIAL_INSIDERS != '' }}

  alert:
    name: Alert to Discord
    if: failure()
    needs: [ artifacts, docs ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to Discord
        if: "always() && github.repository == 'BetonQuest/BetonQuest'"
        run: |
          bash .github/scripts/discord_cache_alert.sh
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
